### ISSUE TITLE
Cancelling a print job causes Octoprint to stop. has to be restarted from SSH session

### ISSUE THREAD

**Issue by KalixtShawxo** [OctoPrint/OctoPrint#4286] opened 2021-10-28 04:02 UTC
### The problem

I have an intermittent problem with OP stopping when I cancel a print job. 
I had thought it was a problem with the SD card (OS corrupt) or the VGA666 hat, 
I removed the VGA666 and I got a new SD Card. I installed a new image of OctoPi to the card, setup my cameras, restore OctoPrint from backup and have been testing the last couple days. 
There were no problems cancelling from the LCD controller at the printer yet. 
But now I cancelled a print job from Octoprint and the service stopped running. 
The only way to get it working again is to SSH into the Pi and run "sudo service octoprint restart"
everything else still seemed to be okay, but the service would randomly stop after a job being cancelled. 

I did try it in safe mode when it rebooted and it did not happen, but the problem is random as to when it happens after a cancel. 

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

I did test in safe mode and it worked, but problem is intermittent in general 

### Version of OctoPrint

1.7.0

### Operating system running OctoPrint

OCtoPi 0.18.0

### Printer model & used firmware incl. version

Ender 3 Pro, MArlin 2.0.9.1

### Browser and version of browser, operating system running browser

Chrome, latest version

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20211028050016.zip](https://github.com/OctoPrint/OctoPrint/files/7430989/octoprint-systeminfo-20211028050016.zip)

**Comment by foosel** [comment] 2021-11-10 12:15
Any updates on this?

**Comment by KalixtShawxo** [comment] 2021-11-10 12:44
I have no update. I have resolved the reported power issue. But have not resolved the issue with the system being restarted on a cancel. I am about to go through and remove most of the plugins and go from there. 

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 10, 2021 at 7:15, Gina ***@***.***> wrote:   


Any updates on this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by foosel** [comment] 2021-11-23 18:34
How about the following... I'll close this now because right now there's simply nothing we can do here without even knowing if it reproduces in safe mode or not, and you can always just request a reopen when you have had a chance to confirm it's not caused by a plugin.

**Closed by foosel** 2021-11-23 18:34 UTC
Labels: needs information, triage

**Comment by KalixtShawxo** [comment] 2021-11-23 18:45
Ok. I plan to work on it this week while I am off work. I will let you know.

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 23, 2021 at 13:34, Gina ***@***.***> wrote:   


How about the following... I'll close this now because right now there's simply nothing we can do here without even knowing if it reproduces in safe mode or not, and you can always just request a reopen when you have had a chance to confirm it's not caused by a plugin.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
