### ISSUE TITLE
Failed octoprint update

### ISSUE THREAD

**Issue by TheTomasVideos** [OctoPrint/OctoPrint#3499] opened 2020-03-31 10:54 UTC
I tried to update octoprint to the latest version but I always got an error message:
**The update did not finish successfully. Please consult octoprint.log and plugin_softwareupdate_console.log for details.**
I don't know what to do now ... I'm a beginner, could somebody help me .. PS: I use OrangePiZero with Armbian. My version of octoprint is 1.3.8 and I'm trying to update it to 1.4.0.
[octoprint LOG.log](https://github.com/OctoPrint/OctoPrint/files/4408506/octoprint.LOG.log)
[plugin_softwareupdate_console LOG.log](https://github.com/OctoPrint/OctoPrint/files/4408507/plugin_softwareupdate_console.LOG.log)

**Comment by foosel** [comment] 2020-03-31 10:57
Looks like an outdated environment and a duplicate of #3484, see the discussion in there for possible fixes and if you still need help get in touch on the community forums at community.octoprint.org please.

**Closed by foosel** 2020-03-31 10:57 UTC
