### ISSUE TITLE
Restore errors in Python 3

### ISSUE THREAD

**Issue by jneilliii** [OctoPrint/OctoPrint#3722] opened 2020-09-11 02:10 UTC
#### What were you doing?

1. Fresh install of octopi 0.18 nightly.
2. During Initial Setup Wizard use backup to restore from.
3. Error in octoprint.log indicates a python 3 related issue, and I assume this also prevents displaying the list of unknown plugins.

#### What did you expect to happen?

Restore to complete without errors.

#### What happened instead?

Error message logged in OctoPrint

#### Did the same happen when running OctoPrint in safe mode?

N/A

#### Version of OctoPrint

1.4.2

#### Operating System running OctoPrint

OctoPi 0.18 nightly (2020-09-09_2020-05-27-octopi-buster-lite-armhf-0.18.0)

#### Printer model & used firmware incl. version

N/A

#### Browser and version of browser, operating system running browser

N/A

#### Link to octoprint.log

[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/5205535/octoprint.log)

#### Link to contents of terminal tab or serial.log

N/A

#### Link to contents of Javascript console in the browser

N/A

#### Screenshot(s)/video(s) showing the problem:

N/A

I have read the FAQ.

**Comment by foosel** [comment] 2020-09-11 09:28
So this is weird. I had to flash an 0.18 nightly to reproduce this, on a converted 0.17 I was not able to reproduce. No idea why as both show Python 3.7.3 as detected version. In any case, I pushed a fix to `maintenance` for OctoPrint 1.5.0

**Closed** 2020-11-30 14:50 UTC
Labels: approved, bug, done
