### ISSUE TITLE
filament runout doesn't wait for filament change but throws a communication error

### ISSUE THREAD

**Issue by FotoFieber** [OctoPrint/OctoPrint#3877] opened 2020-12-10 21:04 UTC
#### What were you doing?
I was printing with not enough filament on the spool. No problem with a smart filament sensor. :)

1. Start Print with not enough filament
2. When filament marlin unloads the rest of the old filament and prompts to change filament
3. wait.... then there will be a communication error

```
2020-12-10 20:30:37,616 - octoprint.plugins.actioncommands - INFO - Command received: 'action:prompt_end'
2020-12-10 20:30:37,617 - octoprint.plugins.actioncommands - ERROR - No command found for 'action:prompt_end'
2020-12-10 20:30:37,629 - octoprint.plugins.actioncommands - INFO - Command received: 'action:prompt_begin FilamentRunout T0'
2020-12-10 20:30:37,636 - octoprint.plugins.actioncommands - ERROR - No command found for 'action:prompt_begin FilamentRunout T0'
2020-12-10 20:30:37,641 - octoprint.plugins.actioncommands - INFO - Command received: 'action:prompt_show'
2020-12-10 20:30:37,644 - octoprint.plugins.actioncommands - ERROR - No command found for 'action:prompt_show'
2020-12-10 20:30:38,128 - octoprint.util.comm - INFO - Changing monitoring state from "Printing" to "Pausing"
2020-12-10 20:30:38,146 - octoprint.printer.standard.job - INFO - Print job paused - origin: local, path: Faceted_Bowl_2_0.16mm_PLA_ENDER3_8h23m.gcode, owner: mm, user: None
2020-12-10 20:30:42,167 - octoprint.util.comm - INFO - Communication timeout while printing, trying to trigger response from printer.
2020-12-10 20:30:42,198 - octoprint.util.comm - INFO - Changing monitoring state from "Pausing" to "Paused"
2020-12-10 20:30:45,213 - octoprint.util.comm - INFO - Communication timeout while printing, trying to trigger response from printer.
2020-12-10 20:30:48,227 - octoprint.util.comm - INFO - No response from printer after 3 consecutive communication timeouts, considering it dead.
2020-12-10 20:30:48,316 - octoprint.util.comm - INFO - Changing monitoring state from "Paused" to "Offline (Error: *T*oo many consecutive timeouts, printer still connected and alive**?)"
2020-12-10 20:30:48,475 - octoprint.plugins.tracking - INFO - Sent tracking event commerror_timeout, payload: {u'commerror_text': u'Too many consecutive timeouts, printer still connected and alive?'}
2020-12-10 20:30:50,026 - octoprint.plugins.webhooks - INFO - P EVENT Error - There was an error.
```

#### What did you expect to happen?

I epected octoprint to wait until I have changed filament.

#### What happened instead?
Octoprint reported a communication error.

#### Did the same happen when running OctoPrint in safe mode?
Did not try that.

I can try to reproduce this in safe mode if you think it really helps.

#### Version of OctoPrint

Version 1.5.1
#### Operating System running OctoPrint
Octopi 

Version 0.17.0, running on Raspberry Pi 4 Model B Rev 1.2

#### Printer model & used firmware incl. version
Biqu B1 with self compiled marlin 2.0.x bugfix

#### Browser and version of browser, operating system running browser
No active browser when error occured.

#### Link to octoprint.log

https://gist.github.com/FotoFieber/007075a4197983883e2ee06107b3ad28

I know, webhook is not configured yet. :)

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by cp2004** [comment] 2020-12-10 21:26
This is not an OctoPrint issue, and instead must be addressed upstream. Also a duplicate of #3862, so I wonder if this is a common issue in Marlin.

Per [my response over there](https://github.com/OctoPrint/OctoPrint/issues/3862#issuecomment-739243941) the firmware must still respond while there is a filament change, since OctoPrint should be able to do all the things it should be able to such as move the head, retract filament (if you wanted it to), purge new filament, and then resume the print. The printer *should not* become unresponsive - it should still respond to something, even if it is 'Wait, I've run out of filament', it is still a response.

**Closed by cp2004** 2020-12-10 21:26 UTC
Labels: approved, triage
