### ISSUE TITLE
[Request] Make Login User Name Credential Not Case Sensitive 

### ISSUE THREAD

**Issue by QuinnDamerell** [OctoPrint/OctoPrint#4219] opened 2021-08-25 22:51 UTC
### Is your feature request related to a problem? Please describe.

Just something to think about. I have gotten a lot of confusion and feedback on OctoEverywhere where the user has trouble logging into OctoPrint because they don't realize the user name is case-sensitive. I know that coming from a technical Linux background that might seem obvious, but I think for the average user it's not something they would expect. 

Even worse, I don't think the error message helps the user by indicating the user name can't be found, leaving the user confused and with no obvious paths to go down. Most users think the issue is with their password, which they believe they entered correctly. (I know there are some security reasons to not reveal that the user name entered doesn't match or exist)

### Describe the solution you'd like

Ideally, the user name used to log in the user shouldn't be case sensitive. 

I was looking at the code but I can't quite gauge how hard it would be to fix it. I was thinking along the lines of always making the user's input from the login API always lower case, and then keeping the dictionary of user accounts key lower case strings. But I'm not sure if that would break other parts of the server as well.

If this change is implemented, there would also be a migration case where the user might have two users set up what would collide if they are both lower case. I'm not sure how to deal with that, but I would be most users wouldn't have done that intentionally.

**Comment by foosel** [comment] 2021-09-13 07:55
Since it being case-sensitive was actually a bug/regression, I opened #4226 for that and solved it. Will be fixed on 1.7.0rc3. Closing this.

**Closed by foosel** 2021-09-13 07:55 UTC
Labels: request
