### ISSUE TITLE
[Request] Gcode viewer to report moves outside build volume

### ISSUE THREAD

**Issue by OldCurmudgeon3DP** [OctoPrint/OctoPrint#3893] opened 2020-12-17 16:07 UTC
**Is your feature request related to a problem? Please describe.**
Sort of. I lost a 16hr print, only 30% in, when a travel move was requested that went beyond the build volume of the printer. The slicer should have flagged the problem first, but didn't.

**Describe the solution you'd like**
Would it be possible to warn the user before the job starts that it has moves outside the bed size defined in Octoprint?

**Describe alternatives you've considered**
I've submitted a bug report to the slicer developer, but this would be a good sanity check in case the user sends the file to the wrong printer, e.g. a prusa mini when the file needs the volume of a CR-10. 
The analysis shows the part dimensions, but apparently does not include the travel moves.

**Additional context**
There were 4 layers that broke the boundary for this print. Here's the first. It was 0.35mm too far in X. *sadface* 
I could set the firmware bed size 5mm larger in X, but I don't want to. Even though the head can safely move the distance, the nozzle would be off the bed surface.

![gcode-view](https://user-images.githubusercontent.com/44645861/102511724-214da080-4057-11eb-86c3-24ecdc5e4304.png)

**Comment by cp2004** [comment] 2020-12-17 16:12
This is already a feature, if the bed size is set correctly (printer profile) and it is enabled:
![image](https://user-images.githubusercontent.com/31997505/102512884-73f08200-4082-11eb-8141-393b1783fbdc.png)

If this did not work, then maybe there is something wrong with it 🤷‍♂️ but in which case you can submit a bug report 🙂. Check you have it enabled, and that your bed size is correctly configured.

**Comment by ProfEngr** [comment] 2020-12-17 16:44
I checked my settings... The model itself does not report as too large for the bed. It's the travel moves from the slicer using *avoid crossing perimeters* that caused the failure.

Should I start a new issue or can this one be changed to a bug report?

![octo-printerprofile](https://user-images.githubusercontent.com/44645861/102516410-ce76e780-405c-11eb-948d-a06cad3a588c.png)

![octo-features](https://user-images.githubusercontent.com/44645861/102516425-d33b9b80-405c-11eb-8541-b159449fe5db.png)

**Comment by cp2004** [comment] 2020-12-17 16:46
Upload the gcode here, I will take a look and decide. Not sure how the model size detection works but I don't think it'll take me long to find out. Will let you know if it looks like a bug.

**Comment by ProfEngr** [comment] 2020-12-17 17:09
The first offending G1 is on line 138572.

[Chute1-red.zip](https://github.com/OctoPrint/OctoPrint/files/5711021/Chute1-red.zip)

**Comment by cp2004** [comment] 2020-12-17 17:27
Thanks, I dug through the source and it seems model size detection only works for moves *with extrusion*, per:

https://github.com/OctoPrint/OctoPrint/blob/bf8ff6358556aaa073da2d0646f193c3a1fef48f/src/octoprint/util/gcodeInterpreter.py#L389-L393

So this request becomes 'detect movements outside the print volume' in gcode analysis I guess, since it is by design it ignores the travel moves for model size detection. Makes sense for model size, since travel moves at the start/end of a print would always make the size 'bed size' - so this could be decoupled to work out if travel moves are outside the print volume, provide a separate warning.

**Comment by ProfEngr** [comment] 2020-12-17 18:52
What I'll do in the meantime, if I have a print near the extents, is enable travel moves in the preview and/or open the gcode file in Notepad++ and search for values greater than the bed dimension. Maybe the slicer devs will eventually try to account for this on their end too.

**Comment by foosel** [comment] 2022-09-28 12:37
Implemented in #4579 (thanks @kForth!) and now merged, will be in 1.9.0!

**Comment by foosel** [comment] 2023-05-23 09:49
1.9.0 has been released.

**Closed by foosel** 2023-05-23 09:49 UTC
Labels: request, done
