### ISSUE TITLE
[Request] Update after next print

### ISSUE THREAD

**Issue by johnbchron** [OctoPrint/OctoPrint#4318] opened 2021-11-22 17:37 UTC
### Is your feature request related to a problem? Please describe.

Sort of. Most of the time when an update is published for a plugin or OctoPrint itself, I only see it when I pull up the OctoPrint interface to start a print. Updates block prints, take a bit of time, and sometimes cause behavioral changes, so I rarely decide to update when I'm about start a print. The consequence of this is that sometimes I can go a long time without updating because I only think about it / am reminded of it when it's inconvenient for me to start the update.

### Describe the solution you'd like

I think a really simple solution to this would be to add a "Update after next print" button to update prompts. I suppose I don't have a specific reason why it can't become a plugin but I feel like it concerns OctoPrint's core functionality and solves an issue that potentially exists for all users.

### Describe alternatives you've considered

I haven't considered alternatives because this is the only solution I thought of.

**Comment by foosel** [comment] 2021-11-23 17:50
Duplicate of #3589

**Closed by foosel** 2021-11-23 17:50 UTC
Labels: request
