### ISSUE TITLE
Action trigger bug

### ISSUE THREAD

**Issue by pertoft** [OctoPrint/OctoPrint#4058] opened 2021-03-25 10:12 UTC
### The problem

1. Fillament run out sensor triggered (faulty)
2. Octoprint threw an exception and the server restarted - print failed

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

The plugins are disabled in safemode

### Version of OctoPrint

1.5.3

### Operating system running OctoPrint

Raspbian GNU/Linux 10 (buster)

### Printer model & used firmware incl. version

Creality CR-10 Marlin 2.0.x

### Browser and version of browser, operating system running browser

Chrome lastest release

### Checklist of files to include below

- [X] octoprint.log
- [ ] serial.log or contents of your terminal tab (always include in cases of issues with printer communication)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

octorpint.log: http://paste.debian.net/1190905/
serial.log: disabled

The server restarted before i was able to capture output, but telegram log suggested the fillament was run out due to a PAUSE message.

**Comment by foosel** [comment] 2021-03-25 10:48
I don't see an OctoPrint restart caused by the logged exception here. The exception is caused by an error in the third party actiontrigger plugin, [its method signature is wrong](https://github.com/Booli/OctoPrint-ActionTriggerPlugin/blob/master/octoprint_actiontrigger/__init__.py#L71), it should have `*args, **kwargs` at the end of parameter list to also be able to cope with newly introduced parameters since its creation, but it doesn't have that. I'm not sure if the plugin is actively maintained anymore, AFAIK @Booli isn't really into 3d printing anymore and the plugin was one of the first ever.

The exception gets properly caught and the processing on OctoPrint's side proceeds as expected. The only server restart I see is caused by an intentional shutdown after an update:

```
2021-03-24 15:27:01,856 - octoprint.plugins.softwareupdate - INFO - Restarting...
2021-03-24 15:27:02,000 - octoprint.server - INFO - Shutting down...
2021-03-24 15:27:02,457 - octoprint.server - INFO - Calling on_shutdown on plugins
2021-03-24 15:27:02,457 - octoprint.events - INFO - Processing shutdown event, this will be our last event
2021-03-24 15:27:02,470 - octoprint.events - INFO - Event loop shut down
2021-03-24 15:27:03,086 - octoprint.plugins.tracking - INFO - Sent tracking event shutdown, payload: {}
2021-03-24 15:27:03,096 - octoprint.plugins.HeaterTimeout - INFO - Shutting down...
2021-03-24 15:27:03,264 - octoprint.server - INFO - Goodbye!
2021-03-24 15:27:04,788 - octoprint.startup - INFO - ******************************************************************************
2021-03-24 15:27:04,790 - octoprint.startup - INFO - Starting OctoPrint 1.5.3
2021-03-24 15:27:04,790 - octoprint.startup - INFO - ******************************************************************************
```

I also see neither a print cancellation nor a disconnect in the whole log.

Closing this since as far as I can see from the data you provided, this is strictly a third party plugin issue that needs to be solved in the plugin, there is no evidence of any issues caused by this in OctoPrint in your log.

**Closed by foosel** 2021-03-25 10:48 UTC
Labels: triage
