### ISSUE TITLE
Python 3.11 Support

### ISSUE THREAD

**Issue by cbxbiker61** [OctoPrint/OctoPrint#4678] opened 2022-10-31 08:45 UTC
### Is your feature request related to a problem? Please describe.

I've upgraded to Python 3.11 and have the following error when starting Octoprint  By changing wrapt dependency to >= 1.14.1 the problem goes away..

File "/home/octoprint/OctoPrint/lib/python3.11/site-packages/octoprint/access/users.py", line 11, in <module>
Oct 31 02:06:01 mk3.internal octoprint[734]:     import wrapt
Oct 31 02:06:01 mk3.internal octoprint[734]:   File "/home/octoprint/OctoPrint/lib/python3.11/site-packages/wrapt/__init__.py", line 10, in <module>
Oct 31 02:06:01 mk3.internal octoprint[734]:     from .decorators import (adapter_factory, AdapterFactory, decorator,
Oct 31 02:06:01 mk3.internal octoprint[734]:   File "/home/octoprint/OctoPrint/lib/python3.11/site-packages/wrapt/decorators.py", line 34, in <module>
Oct 31 02:06:01 mk3.internal octoprint[734]:     from inspect import ismethod, isclass, formatargspec
Oct 31 02:06:01 mk3.internal octoprint[734]: ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/python3.11/lib/python3.11/inspect.py)

### Describe the solution you'd like

Change wrapt dependency to >= 1.14.1.

[octoprint-systeminfo-20221031024700.zip](https://github.com/OctoPrint/OctoPrint/files/9899510/octoprint-systeminfo-20221031024700.zip)

**Comment by foosel** [comment] 2022-10-31 08:57
Duplicate of #4488

**Closed** 2022-10-31 09:02 UTC
Labels: triage
