### ISSUE TITLE
[Request] Delay showing (Update Available - Plugins) while printing

### ISSUE THREAD

**Issue by BaileyMillerSSI** [OctoPrint/OctoPrint#4138] opened 2021-05-13 13:09 UTC
### Is your feature request related to a problem? Please describe.

As of right now updating a plugin requires rebooting the print server which interrupts prints. As well there isn't a way to make the (Update Available) window delay or postpone. So if I am deep into a really long print and a plugin update notification appears I just have to leave it for X hours until my print is over. 
![9HObazomxm](https://user-images.githubusercontent.com/14271740/118129732-8c16c400-b3ca-11eb-9fbc-9f854d0ae919.png)

### Describe the solution you'd like

Either the plugin update check shouldn't be running during a print or the update window shouldn't display while a print is running. After a the status changes from printing to anything else the popup can display. 

### Describe alternatives you've considered

I like to keep everything up to date but I fear if the ignore the popup I'll forget/miss updates. I could simply ignore it but then I may forget about it.

**Comment by foosel** [comment] 2021-11-23 18:40
Duplicate of #3589

**Closed by foosel** 2021-11-23 18:40 UTC
Labels: request
