### ISSUE TITLE
As of 1.5.0, the blocked commands setting can't be cleared 

### ISSUE THREAD

**Issue by lciscon** [OctoPrint/OctoPrint#3867] opened 2020-12-05 20:35 UTC
#### What were you doing?

I was trying to delete the blocked commands (M0,M1) set in the  Firmware & protocol tab of the Serial Connection settings dialog.

#### What did you expect to happen?

I expected that I could delete the commands like I could do in earlier versions (1.4)

#### What happened instead?

If I remove the contents of that setting and hit the Save button, the old contents (M0, M1) reappears right before the dialog closes. If I then re-open the dialog the old contents are in that row (M0, M1).

If I delete the contents, save and close the dialog, reboot Octoprint and then re-open the dialog the old values are still there (M0, M1).

If I CHANGE the contents to a new string with the exact same length (M1, M2), save, close and reopen it retains the new value (M1,M2). And I have verified that this value is actually active.

I verified that the behavior worked correctly in 1.4 (i.e. you can delete the value just fine).

#### Did the same happen when running OctoPrint in safe mode?

Yes

#### Version of OctoPrint

1.5.1

#### Operating System running OctoPrint

Octopi 0.17.0

#### Printer model & used firmware incl. version

Northworks 600x.  Firmware v. 1.6

#### Browser and version of browser, operating system running browser

Chrome Version 87.0.4280.67 

#### Link to octoprint.log

https://gist.github.com/lciscon/0bc5ad953f8ce9db532e8147eb0e7218

#### Link to contents of terminal tab or serial.log

N/A

#### Link to contents of Javascript console in the browser

![Screen Shot 2020-12-05 at 2 29 03 PM](https://user-images.githubusercontent.com/7740478/101262704-40b70600-3706-11eb-846b-3edb79c12eaa.png)

#### Screenshot(s)/video(s) showing the problem:

![Screen Shot 2020-12-05 at 1 30 03 PM](https://user-images.githubusercontent.com/7740478/101262714-4dd3f500-3706-11eb-8ec5-dff481e59d56.png)

I have read the FAQ.

**Comment by jneilliii** [comment] 2020-12-05 21:05
confirmed, I'm able to reproduce.

**Comment by jneilliii** [comment] 2020-12-05 21:07
I also noticed in an attempt at a workaround that if you just put on item in there the second item from before gets put in.

![image](https://user-images.githubusercontent.com/5249455/101265378-f6d51c80-3713-11eb-94a2-37e673ab4e3d.png)

**Comment by jneilliii** [comment] 2020-12-05 21:10
@lciscon if you use `SOMETHING1, SOMETHING2` it will stick and give you the desired effect as a temporary workaround.

**Comment by cp2004** [comment] 2020-12-05 22:05
Looks like an issue in the client side - the debugger says data is never sent to the server if they are deleted, however it *is* if they are changed.

**Comment by cp2004** [comment] 2020-12-05 22:38
This actually doesn't work with any of the comma separated lists, maybe other settings too.

Documenting how far I have got narrowing this down.
* The data is **wrong** when it comes out of the viewmodel - it remains ["M0", "M1"] in the observable:
   https://github.com/OctoPrint/OctoPrint/blob/38256815ef6d6dd602e0fac949a17fbf8f30f838/src/octoprint/static/js/app/viewmodels/settings.js#L985
* The data processed from the special mapping is **correct**, from here, returns []:
https://github.com/OctoPrint/OctoPrint/blob/38256815ef6d6dd602e0fac949a17fbf8f30f838/src/octoprint/static/js/app/viewmodels/settings.js#L1179-L1180

* Then when merged, the empty data is overwritten with the previous data here:
 https://github.com/OctoPrint/OctoPrint/blob/38256815ef6d6dd602e0fac949a17fbf8f30f838/src/octoprint/static/js/app/viewmodels/settings.js#L1182


This appears to be as a result of https://github.com/OctoPrint/OctoPrint/commit/9494db95683ba280ea84bbc440f9db502bd02df4, and I can confirm that rolling back this change fixes this behaviour. So now it is down to @foosel - what was that change fixing, and what can be done instead. Bug analysis done 🙂

**Comment by 12345Josparky** [comment] 2020-12-06 19:51
Ok so if we do a lot of printing that needs the pause what is the correct thing to do as I get this message now at every pause Not sending M0 to printer, it's configured as a blocked command Do we just let octoprint handle the pause or do we need it sending it to the printer as well. I don't know anything at all about this coding but would like to know do I just leave it as is and put up with the message that comes up now every time. Never seen that message before until I updated to 1.5.1 version

**Comment by foosel** [comment] 2020-12-07 11:04
@cp2004 Wow, thank you **SO** much for the legwork you did here!

I have the feeling this and #3845 are actually two symptoms of the same issue. Now I'll need to jog my memory and try to remember what I observed that made me do that change, and then figure out how to achieve the same functionality without breaking list style settings in the UI.

And maybe also push a fixing plugin if possible (I feel this issue to be a bit too low key to merit a full hotfix tbh)

**Comment by foosel** [comment] 2020-12-07 15:13
![image](https://user-images.githubusercontent.com/83657/101368045-f8831980-38a6-11eb-8c20-c000c8460d58.png)

Damn... I overlooked the highlighted part. What's probably happening here is the old array data doesn't get overwritten but instead extended by the new. I didn't expect `merge` to do that for arrays as well. Will need to find a solution that only touches objects, like our `dict_merge` helper on the backend.

**Comment by foosel** [comment] 2020-12-07 15:49
Fixed by the above commit, ready for 1.6.0. Should another hotfix 1.5.2 be need to be pushed, I'll backport this into that. In the meantime I'll whip up a quick plugin to work around this.

**Comment by cp2004** [comment] 2020-12-07 16:42
Good to see I was useful 😄 

Just a bit of tracing through logging to console, then a bit of `git blame` to find the issue. On to the next bug report...

**Comment by foosel** [comment] 2020-12-07 16:46
This plugin should work as a fix for now: https://github.com/OctoPrint/OctoPrint-FixSettingsDeepMerge

Install via plugin manager, get more, from this URL: https://github.com/OctoPrint/OctoPrint-FixSettingsDeepMerge/archive/master.zip

**Comment by lciscon** [comment] 2020-12-07 17:28
Awesome! Thanks everyone!!

**Comment by 12345Josparky** [comment] 2020-12-08 16:39
Ok so I know this is for bug reports but can someone answer this for me please or tell me where to get the answer.

Ok so if we do a lot of printing that needs the pause what is the correct thing to do as I get this message now at every pause Not sending M0 to printer, it's configured as a blocked command Do we just let octoprint handle the pause or do we need it sending it to the printer as well. I don't know anything at all about this coding but would like to know do I just leave it as is and put up with the message that comes up now every time. Never seen that message before until I updated to 1.5.1 version

Thanks

**Comment by foosel** [comment] 2020-12-08 16:48
> Never seen that message before until I updated to 1.5.1 version

It was simply silently suppressing it until 1.5.x. It's always done what it does now, just silently. There was confusion by some people over commands getting silently suppressed, so when commands are now suppressed they generate a heads-up for the user in form of a notification. If everything has always worked for you so far, then the behaviour of blocking the command is still correct and you don't need to do anything at all.

OctoPrint by default suppresses `M0` and `M1` and instead pauses on its end since most firmware out there would read `M0`/`M1` as a command to pretty much commit suicide until a button is pressed on the printer - not what you usually want.

Btw, you can also disable these notifications altogether via Settings > Serial Connection > Behaviour > Sanity Checking:

![image](https://user-images.githubusercontent.com/83657/101514401-803b5780-397d-11eb-9510-ac7962b6b8b4.png)

**Comment by 12345Josparky** [comment] 2020-12-08 19:21
Thank you for the better explanation. So probably best for me to just leave it like it is and close the popup then?? If I disable the checking will that not block some other checks that I might need to see?? Can the M0 and M1 commands bee removed like this fix does without harm?? sorry for so many questions just trying to understand all this from a dummy point.

**Comment by foosel** [comment] 2020-12-09 14:25
> Can the M0 and M1 commands bee removed like this fix does without harm??

Removed from the GCODE, yes. Removed from the block list, I wouldn't recommend it, because then your printer will get them sent and the *firmware* will handle those commands, which means hard lock until you press a button (at least according to spec).



> If I disable the checking will that not block some other checks that I might need to see??

Well, any related to blocked commands, yes. Unchecking that will return to the old behaviour before 1.5.x.



> So probably best for me to just leave it like it is and close the popup then??

Yes. If you use `M0`/`M1` to pause your prints to do whatever, you can also inject `@pause` instead, see https://docs.octoprint.org/en/master/features/atcommands.html

**Closed** 2020-12-10 12:33 UTC
Labels: approved, bug, done

**Comment by foosel** [comment] 2020-12-10 12:34
About to release 1.5.2 after all (third party dependency released a breaking update), so this fix gets a hotfix release after all.

**Comment by 12345Josparky** [comment] 2020-12-10 17:15
Thanks foosel
