### ISSUE TITLE
[Request] Please allow to rename jobs (gcode files) and "star" those to keep.

### ISSUE THREAD

**Issue by AndKe** [OctoPrint/OctoPrint#4693] opened 2022-12-15 13:43 UTC
### Is your feature request related to a problem? Please describe.

![Screenshot from 2022-12-15 14-34-35](https://user-images.githubusercontent.com/1468842/207872652-6584d0e8-14cd-45ed-93dc-a2b95e69aa19.png)

### Describe the solution you'd like

When working with FreeCad and/or other tools, exported items may get different names.
Then - the objects might be duplicated in the slicer - so even if a job is automatically named: "Mount for xyz"  - it can be desired to save it as "3x Mount for xyz"   or something that describes the material and surface: "Mount for xyz - PLA on PEI"

Please allow renaming files. - good jobs may be worth saving.

Also: the files have properties like upload date, printed date and so on. It would be very nice to have a simple bool attribute "starred"  - then the file list could be sorted by "starred" (worth keeping jobs)   - with good names.

**Comment by jneilliii** [comment] 2022-12-15 13:59
Try pressing that little cut/scissor button and putting in a new name?

**Comment by foosel** [comment] 2023-01-16 16:54
As stated by @jneilliii, renaming (and moving) is already possible via the scissors icon. Which makes this a request to be able to star dear-to-heart print jobs. And that makes it a duplicate of #3433

**Closed by foosel** 2023-01-16 16:54 UTC
Labels: request
