### ISSUE TITLE
[Request] Confirm deleting of file

### ISSUE THREAD

**Issue by BloodyIron** [OctoPrint/OctoPrint#5025] opened 2024-05-29 03:18 UTC
### Is your feature request related to a problem? Please describe.

We need a "are you sure?" confirmation dialogue when deleting files for extremely obvious reasons (do you really need me to explain why?)

### Describe the solution you'd like

We need a "are you sure?" confirmation dialogue when deleting files for extremely obvious reasons (do you really need me to explain why?)

**Comment by foosel** [comment] 2024-05-29 07:55
Duplicate of #833

**Closed by foosel** 2024-05-29 07:55 UTC
Labels: request
