### ISSUE TITLE
Odd Temperature Graph behavior during ABL. 

### ISSUE THREAD

**Issue by FrostyWolf** [OctoPrint/OctoPrint#2830] opened 2018-09-23 08:02 UTC
#### What were you doing?

1. I am using the following start gcode:
```M190 S64 ; set bed to 64
M104 S165 ; preheat hotend during start up
M82 ;absolute extrusion mode
G28 ;Home
G1 Z15.0 F6000 ;Move z 15mm
G29 ; BLTOUCH
M109 S190 ; Set hotend temp
```
2. Click print
3. Watch the temp graph

#### What did you expect to happen?
I expected that after the bed finished heating (M190 S64), that the target temp for the tool would be set to 165 (M104 S165).  Then, after ABL Probe (G29) I expect the target temp for the tool to be set to 190 (M109 S190).  
#### What happened instead?
Those things all happened on the printer, but are not properly represented on the graph.  

The graph shows the Target Temperature gradual raises over time (which it doesn't) and shows the Actual Temperature of the tool instantly going from 26 degrees to 165, then gradually raising to 190.

From what I can tell, It's because the printer can't (or won't?) send data while the mesh test is running.  
Recv: echo:busy: processing
I'm 99% sure this is the printers problem and nothing that OcotoPrint is doing wrong.  The main reason I am reporting is because the graph should be reporting a temperature "jump" for Target Temperature, and curve for Actual Temperature, not the other way around.  I know it's not receiving temperature data, but it's still showing a gradual increase in Target Temperature for some reason, so at the very least I don't think that should be appearing like that.
#### Did the same happen when running OctoPrint in safe mode?
Yes

#### Version of OctoPrint
OctoPrint 1.3.9

#### Operating System running OctoPrint
 OctoPi 0.15.1

#### Printer model & used firmware incl. version
Ender 3 - TH3D_UFW_U1.R2.1d

#### Browser and version of browser, operating system running browser
Google Chrome - Version 69.0.3497.100 (Official Build) (64-bit)
Microsoft Windows 10 - Version 1803 (OS Build 17134.285)

#### Link to octoprint.log
https://pastebin.com/Z2FNd7cp

#### Link to contents of terminal tab or serial.log
https://pastebin.com/hb0HaqXa

#### Link to contents of Javascript console in the browser
https://pastebin.com/zCeQwzic

#### Screenshot(s)/video(s) showing the problem:
https://i.imgur.com/NPfwgUP.png

I have read the FAQ.

*edit by @foosel: fix screenshot link*

**Comment by LazeMSS** [comment] 2021-03-31 19:10
Closing - its by design/how data is stored.

**Closed by LazeMSS** 2021-03-31 19:10 UTC
Labels: approved, improvement
