### ISSUE TITLE
GPX plugin won't install.  OctoPrint 1.4.2, Windows 10

### ISSUE THREAD

**Issue by rkweber** [OctoPrint/OctoPrint#3713] opened 2020-08-31 12:18 UTC
#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by cp2004** [comment] 2020-08-31 12:23
Duplicate of #3698, which is solved by the PR #3707 - should be in the next release, scheduled as 1.5.0

For a workaround, please see https://github.com/markwal/OctoPrint-GPX/issues/85#issuecomment-682200814

Thanks for the report, but in future filling out the template would be appreciated 🙂

**Closed by cp2004** 2020-08-31 12:23 UTC
Labels: status:duplicate
