### ISSUE TITLE
[Request] Update after print finishes

### ISSUE THREAD

**Issue by tjjfvi** [OctoPrint/OctoPrint#3320] opened 2019-10-27 18:13 UTC
**Is your feature request related to a problem? Please describe.**
The main reason I go to octoprint is to print something or to check on a print. Sometimes it notifies me of updates. At that point, I either don't want to wait or can't update, because a print is running. 

**Describe the solution you'd like**
It would be nice if I could tell it to "update after next/current print" (or similar).

**Describe alternatives you've considered**
Optional auto-updates could also be a solution.

**Additional context**
N/A

**Comment by foosel** [comment] 2021-11-23 17:50
While #3589 is a duplicate of that, I didn't realize it until it had received a bunch of upvotes already. Since we can't transfer them, I'm closing this request as a duplicate of #3589 (even though it was earlier) and suggest anyone interested in this a) give #3589 a thumbsup on the issue text and b) follow that instead.

**Closed by foosel** 2021-11-23 17:50 UTC
Labels: request
