### ISSUE TITLE
Webcam Stream Loading... Safari 

### ISSUE THREAD

**Issue by KaJashey** [OctoPrint/OctoPrint#4863] opened 2023-07-30 18:23 UTC
### The problem

The problem: Octoprint 1.9.2 and earlier. Intermittently when viewing the control tab in Safari I get a message "Webcam Stream Loading..." and the video does not load.

To fix the problem: Clear cache and restart Safari:

To cause the problem to reoccur: Open two browser tabes with the Octoprint: Control tab open. The second browser tab will have the "Webcam Stream Loading..." message while the first plays video. Closing those two browser tabs and opening another gets the "Webcam Stream Loading..." message. This persists till cache is cleared and browser is restarted.

This doesn't not happen on Chrome: Chrome can have two browser tabs with the control window open and video streams to each.

Will try to report to Apple/Safari team as well

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

Currently printing a big print

### Version of OctoPrint

1.9.2

### Operating system running OctoPrint

Linux

### Printer model & used firmware incl. version

 Prusa Mk3S+ - Firmware 3.13.0 

### Browser and version of browser, operating system running browser

Safari 16.5.2 /605.1.15 Mac OS Ventura 13.4.1(c)

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[systeminfo.txt.zip](https://github.com/OctoPrint/OctoPrint/files/12209838/systeminfo.txt.zip)

**Comment by foosel** [comment] 2023-07-31 09:07
> ### If you could not test in safe mode, please state why
> 
> Currently printing a big print

As it says *right in the issue form*, "currently printing a big print" is **not** an excuse to not test in safe mode! Please finish your big print, then test in safe mode, then get back to us on whether the issue persists. 

This is not to annoy you, this is because a lot of issues are caused by third party plugins which get disabled in safe mode, and debugging stuff that is not even part of core OctoPrint costs valuable time that is then not available for hunting actual core bugs or improving things in general for everyone.

**Comment by wolfgangrumpf** [comment] 2023-09-25 19:48
I actually am having a problem that may be related - webcam was working fine then just stopped working; if I run **sudo service camera-streamer restart** it typically fixes it, at least for a while....

**Comment by foosel** [comment] 2023-10-02 09:49
@wolfgangrumpf that rather sounds like ayufan/camera-streamer#94

**Comment by foosel** [comment] 2024-08-19 09:54
Closing as there's been no additional information provided in a year by the OP, and it's likely a Safari issue in either case and thus out of scope here.

**Closed by foosel** 2024-08-19 09:54 UTC
Labels: unreproduced, triage
