### ISSUE TITLE
[Request] Ability to ignore Printer Notifications based on regex

### ISSUE THREAD

**Issue by dburr** [OctoPrint/OctoPrint#4326] opened 2021-11-29 00:03 UTC
### Is your feature request related to a problem? Please describe.

I use the [Detailed Progress](https://plugins.octoprint.org/plugins/detailedprogress/) plugin to update my printer's display with the estimated time to completion, etc. It does this by periodically injecting `M117` commands to the printer. Unfortunately since `M117` commands are echoed back as notification actions, this results in the "Printer Notifications" list getting filled with useless/trivial notifications such as this.
![Screenshot from 2021-11-28 15-58-37](https://user-images.githubusercontent.com/1237762/143791639-23e5d963-af98-4b85-92eb-87679234cd8f.png)

It would be even worse if I had popups enabled, as then I would have these trivial messages constantly popping up. I have actually wanted to enable popups so that I can be alerted of truly important/noteworthy things (filament runout, thermal runaway, etc.) but enabling popups with the situation like this would be infuriating.

### Describe the solution you'd like

It would be nice to be able to conditionally ignore notifications from the printer based on a regex. So, for example, to filter out the useless messages in my screenshot above, I would use regexes like:

`^\d+%`
`^Layer \d+\/\d+`
`^Done In .*`
`^(Mon|Tue|Wed|Thu|Fri|Sat|Sun).*`

### Describe alternatives you've considered

Obviously I could disable the Detailed Progress plugin, but then I would miss out on that useful information being shown on the printer (which I do check periodically)

**Comment by foosel** [comment] 2021-11-29 09:17
> Unfortunately since `M117` commands are echoed back as notification actions

TBH, that sounds more like the firmware is abusing the printer notification feature. It's meant for notifications that are NOT triggered by the host itself but would otherwise require the user to stand in front of the printer to even have a knowledge of. Sadly this feature has seen a TON of abuse like this ever since I added it to OctoPrint, to a point where I wonder whether it was a good idea to add it at all, with firmware happily spamming its users through it.

We can look into a filter here, but **please** also report this to your firmware issue tracker so that may look into fixing this constant spam on their end as well.

**Comment by jneilliii** [comment] 2021-11-29 13:41
Marlin has been doing this for a while now. I think it may have been utilizing this to support the newer touch screen interfaces.

**Comment by foosel** [comment] 2021-11-29 13:54
Doesn't change that it's abusing the feature. This isn't the first time I've had to reduce its usability and simplicity on my end due to it getting abused and as a consequence spamming the user (the only reason why there even is a notification AREA now instead of only popups was another case of heavy abuse). It is starting to get ridiculous.

**Comment by lscarneiro** [comment] 2022-04-14 15:57
Is there a way we can at least limit the messages? Like, "keep last `x`"? 

Filtering is definitely a plus, but if we're able to at least limit the number of messages kept, this would help on long prints as the UI gets slow with too many elements on the page.

**Comment by foosel** [comment] 2022-04-14 16:00
I can look into this but **please** also address this with Marlin. This feature is getting abused. I'm forced to reduce its usefulness again and again due to the constant message spam that gets more and more from firmware version to version. I'm currently frankly leaning towards unbundling the related plugin as a consequence. This needs to be addressed on the firmware side as well.

**Comment by lscarneiro** [comment] 2022-04-14 17:00
Isn't it a problem with how this is fired back from `Detailed Progress` / `DisplayLayerProgress` plugins?

I use both plugins (`Detailed Progress` actually uses `DisplayLayerProgress` as a requirement) which looks like is the case for the OP as well.

I can be totally wrong, but I feel like it should be possible for this communication to be filtered out internally (with some new implementation probably) since this relies on `M117` and it is fired from a plugin, maybe there's a way we can work between the plugins and OctoPrint to filter this out. 
I'm just not seeing how Marlin can intervene if this is an `M117` situation, and the bundled plugin spits all the messages to the UI, so how can Marlin know it shouldn't report back to OctoPrint (if this is even the case, sorry, I don't know how this interaction is implemented)

**Comment by jneilliii** [comment] 2022-04-14 17:45
The issue isn't so much the usage of M117 on the firmware side, but the use of action notifications in response to M117 commands. M117 is used to display a message on the LCD screen and is not intended to be an action notification because it's not an action. Marlin was doing this IIRC in order to support the touch screen interfaces and have them display messages on those screens when M117 messages are sent.

**Comment by lscarneiro** [comment] 2022-04-14 18:02
I see... thanks for the clarification 😊 

So, probably the "simplest solution" (not saying it's easy, though), would be to be able to configure a limit of messages shown, then?

**Comment by cp2004** [comment] 2022-04-14 19:44
There's probably a case for a limit such as 30-50 messages? To stop it from getting overwhelmed and causing a performance issue. I just guessed that number out of the air.

The `action:notification` system is not just an OctoPrint specific feature, as @jneilliii says it's useful for touchscreens acting as a host. The issue of 'spam' here is in part caused by OctoPrint plugins sending lots of M117 updates - usually a screen would just show the latest one, here we save them. I'm not going to argue whether that was the original intention of the feature or not.

There was a PR merged recently to allow some configuration of how many notifications are sent (https://github.com/MarlinFirmware/Marlin/pull/22833). Some of the pushback mentioned was further discussed on discord at the time.

**Comment by foosel** [comment] 2022-05-11 08:49
The problem with a limit that I see is that all the spam could then simply flood out the actually meaningful messages. From that perspective a filter regex or something would indeed make more sense.

---

Implementation idea:

- [ ] new filter setting in [`src/octoprint/plugins/action_command_notification/__init__.py`](https://github.com/OctoPrint/OctoPrint/blob/500729607d00069e65ca2105f5af42919d861792/src/octoprint/plugins/action_command_notification/__init__.py#L62-L63)
- [ ] apply filter against incoming messages: [`src/octoprint/plugins/action_command_notification/__init__.py`](https://github.com/OctoPrint/OctoPrint/blob/500729607d00069e65ca2105f5af42919d861792/src/octoprint/plugins/action_command_notification/__init__.py#L108-L126)
- [ ] expose filter setting on settings UI: [`src/octoprint/plugins/action_command_notification/templates/action_command_notification_settings.jinja2`](https://github.com/OctoPrint/OctoPrint/blob/500729607d00069e65ca2105f5af42919d861792/src/octoprint/plugins/action_command_notification/templates/action_command_notification_settings.jinja2)

**Comment by jatin-47** [comment] 2023-09-16 06:01
I want to work on this issue. I see that @DShenkle had opened a PR but he is no longer working on that PR so, should I start working afresh or continue where he left off?

**Comment by jneilliii** [comment] 2023-09-16 11:48
I have a working plugin that does the ignoring part, just not based on regex, but exact match...

https://github.com/jneilliii/OctoPrint-FirmwareErrorHandler

**Comment by foosel** [comment] 2024-04-25 12:00
1.10.0 has been released.

**Closed by foosel** 2024-04-25 12:00 UTC
Labels: request, done
