### ISSUE TITLE
Changing communication timeout results in Exception and (silent) 500 Response

### ISSUE THREAD

**Issue by LinusCDE** [OctoPrint/OctoPrint#3736] opened 2020-09-20 00:59 UTC
#### What were you doing?

1. Go to Settings -> Serial connection -> Intervals & Timeouts
2. Change Communication timeout to some other value (e.g. 15)
3. Hit save and reload the page
4. Go back to the setting again

#### What did you expect to happen?

See my changed setting

#### What happened instead?

The setting remained at 30

#### Did the same happen when running OctoPrint in safe mode?

Yes

#### Version of OctoPrint

EDIT: Forgot that. It's 1.4.2 (stable release)

#### Operating System running OctoPrint

Ubuntu Server 20.04 @ RPi4 -> Docker Container with self-built image of [octoprint-docker](https://github.com/OctoPrint/octoprint-docker) (built image using a slightly [modified fork](https://github.com/LinusCDE/octoprint-docker), but the changes only affect background services and not octoprint itself).

#### Printer model & used firmware incl. version

Ender 5, Marlin TH3D U1.R2.A3 PROTOCOL_VERSION:1.0 MACHINE_TYPE:TH3D BLTouch

#### Link to octoprint.log

serial.log (split because of upload size limit)

- [Part 1](https://pastebin.com/Nk8LsnAr)
- [Part 2](https://pastebin.com/SU4a7cL2)
- [Part 3](https://pastebin.com/cSvMkFwe)
- [Part 4](https://pastebin.com/yQHHwSuH) (with relevant error at the end; also note that I hit "Save" multiple times)

(Just noticed here that an internal exception occurs and a 500 is returned. Even though the save settings dialog doesn't close, I never suspected a 500. Maybe throw a error popup here to let the user now of such bugs.)

#### Link to contents of terminal tab or serial.log

Not applicable

#### Link to contents of Javascript console in the browser

https://pastebin.com/JEdpN1HU

[Video](https://transfer.cosmos-ink.net/cQuPd/2020-09-20%2002-40-13.mp4)

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by cp2004** [comment] 2020-09-20 15:55
Duplicate of #3679 - fixed in maintenance, ready for 1.5.0.

As a workaround, you can install the single file plugin mentioned in there as a patch:

>Fixed on maintenance. Fix also available as a single file plugin, just paste `https://gist.githubusercontent.com/foosel/08fa5c9b5b94ef4532f91c3a01303da1/raw/hotfix_3679.py` into Plugin Manager, install and restart.

**Closed** 2020-09-20 15:55 UTC
Labels: status:duplicate, type:confirmed bug
