### ISSUE TITLE
Ensure browser scrollbars are always visible in Safari

### ISSUE THREAD

**Issue by aep** [OctoPrint/OctoPrint#3987] opened 2021-01-26 12:53 UTC
[edited]

when setting up 0.18.0 using a macbook there appears to be no way to pass the setup wizard beyond "Configure the connectivity check" because the options required to proceed are below the scroll line, and there is no indicator that the wizzard has a scrollable interior.  

<img width="1440" alt="Screenshot 2021-01-26 at 13 50 58" src="https://user-images.githubusercontent.com/136926/105847351-cc9a2f80-5fdd-11eb-9c4f-9936c9d46031.png">
<img width="1440" alt="Screenshot 2021-01-26 at 13 51 01" src="https://user-images.githubusercontent.com/136926/105847361-d0c64d00-5fdd-11eb-9cc5-9a2261eb5eff.png">

**Comment by cp2004** [comment] 2021-01-26 13:33
Can you scroll on the dialog? The buttons should be at the bottom, below the test button but it looks as if there is not enough space for them to be visible. Should be there when you scroll down.

**Comment by foosel** [comment] 2021-01-26 13:35
I don't know what you are running there, but it certainly isn't stock OctoPrint as shipped on OctoPi 0.18.0, because that looks like this at this step:

![firefox_2021-01-26_14-32-43](https://user-images.githubusercontent.com/83657/105851563-8d6edd00-5fe3-11eb-80b2-a69d181cd1f2.png)

Note how half of the steps are missing in your version and the HTML looks completely different. So: What exactly did you download when and where, flashed how and did in between?

**Comment by aep** [comment] 2021-01-26 13:47
> can you scroll on the dialog?

aha! thanks. that wasn't obvious to me.

> Note how half of the steps are missing in your version and the HTML looks completely different.

Well, if you do believe that safari is "wrong", i think its fairly easy to block it and tell the user to use the "correct" browser.

> So: What exactly did you download when and where, flashed how and did in between?

i'm not sure why you'd think i'm lying but i guess the best resolution is to just close this.

**Comment by foosel** [comment] 2021-01-26 13:52
I didn't say you were lying, I didn't blame your browser, so there really is no need for this kind of reaction.

All I know is you flashed some 0.18 image and ran into a problem. I did just flash 0.18.0 as linked from the download page myself to check and could not reproduce this. So something between what you did and what I did was different and resulted in this outcome. In order to figure out what and to potentially help you, I need the questions I asked you answered. If you don't want to answer them, ok, your choice, but then I can't help you. They certainly were not meant as an offense but an attempt to figure out what led up to this result.

**Comment by aep** [comment] 2021-01-26 14:00
ok, feel free to reopen, if you agree this is confusing UX.

apple wants you to use other indicators for scrollable areas, 
but a common hack i believe is to just force them visible.

https://codepen.io/ppolyzos/pen/nDbaq

**Comment by foosel** [comment] 2021-01-26 14:05
So it in fact was a case of "scrollable but not clear that it is scrollable" and you were now able to complete the wizard?

**Comment by aep** [comment] 2021-01-26 14:09
yep exactly. works fine, thanks :)
its just confusing if you have never seen the dialog, and there's no indication that there's more options further down.
On the 2020 macbook the last button also happens to align perfectly so it look like this is intended to be the end.

**Comment by foosel** [comment] 2021-01-26 14:12
Reopening as an improvement request then.

I wasn't aware that Apple apparently decided that visible scrollbars are optional. Questionable UX choice IMHO, precisely due to issues like this one, but whatever. Will see I can implement a workaround for that in OctoPrint 1.6.0.

**Comment by foosel** [comment] 2021-01-26 14:47
The above commit enforces scrollbar visibility if Safari is detected as a browser. Will be in 1.6.0

**Closed** 2021-04-27 09:19 UTC
Labels: approved, done, improvement
