### ISSUE TITLE
"Manage language packs" dialog appears out of nowhere

### ISSUE THREAD

**Issue by frenck** [OctoPrint/OctoPrint#3740] opened 2020-09-22 18:03 UTC
#### What were you doing?

1. Go to OctoPrint Settings
2. Click on Appearance
3. Click on the Title field (place cursor in it)
4. Hit enter.

#### What did you expect to happen?

To save and close the dialog, I guess?
Not entirely sure, but what happened instead, I did not expect.

#### What happened instead?

The "Manage Language Packs..." dialogs opens

#### Did the same happen when running OctoPrint in safe mode?

Yes.

#### Version of OctoPrint

1.5.0.dev199+g786e2f860

#### Operating System running OctoPrint

Debian Linux 10, up to date with stable apt repos.
Python 2.7.18, installed via Pyenv, running in a virtualenv.

#### Printer model & used firmware incl. version

None, virtual printer, not relevant for bug report.

#### Browser and version of browser, operating system running browser

macOS Catalina 10.15.5
Google Chrome Version 85.0.4183.102 (Official Build) (64-bit)

#### Link to octoprint.log

Not relevant for bug report, no information in it.

#### Link to contents of terminal tab or serial.log

Not relevant for bug report, no information in it.

#### Link to contents of Javascript console in the browser

No relevant entries to be found in there.

#### Screenshot(s)/video(s) showing the problem:

![2020-09-22 20 00 37](https://user-images.githubusercontent.com/195327/93919742-64290200-fd0e-11ea-9514-2ba9ca6955db.gif)

I have read the FAQ.

☝️ That line is from the issue template. I'm unsure what I need to do with that? Should there be a checkbox? Or is it a question? Should I answer with "Yes"? Or is it the answer by itself already? :P

**Comment by foosel** [comment] 2020-09-22 18:18
> ☝️ That line is from the issue template. I'm unsure what I need to do with that? Should there be a checkbox? Or is it a question? Should I answer with "Yes"? Or is it the answer by itself already? :P

The latter 😉 And thanks, that looks indeed like a fun bug. I'm going to trust you with the statement on the logs because you are who you are 😜, plus I'm pretty sure it's a form definition issue strictly on the front-end.

**Comment by frenck** [comment] 2020-09-22 18:52
> I'm going to trust you with the statement on the logs because you are who you are 😜

Well, there aren't any. It is probably just a wrong binding. So, the code fromi user interface perspective, doesn't have an error.

**Comment by cp2004** [comment] 2020-09-22 19:16
Can reproduce, something to do with the enter key binding I suspect...

**Comment by foosel** [comment] 2020-09-23 09:26
Default form submit behaviour was interfering, that should now be solved on `maintenance`. Will be part of 1.5.0.

**Comment by Guilouz** [comment] 2020-11-13 23:26
Just try on latest 1.5.0rc1, this issue is still there

**Closed** 2020-11-30 14:50 UTC
Labels: approved, bug, done
